(**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *)

unit shared;

interface

uses
  Classes,
  SysUtils,
  Generics.Collections,
  Thrift,
  Thrift.Utils,
  Thrift.Collections,
  Thrift.Protocol,
  Thrift.Transport;

const
  cshared_Option_AnsiStr_Binary = False;
type
  ISharedStruct = interface(IBase)
    function GetKey: Integer;
    procedure SetKey( const Value: Integer);
    function GetValue: string;
    procedure SetValue( const Value: string);

    property Key: Integer read GetKey write SetKey;
    property Value: string read GetValue write SetValue;

    function Get__isset_Key: Boolean;
    function Get__isset_Value: Boolean;

    property __isset_Key: Boolean read Get__isset_Key;
    property __isset_Value: Boolean read Get__isset_Value;
  end;

  TSharedStructImpl = class(TInterfacedObject, IBase, ISharedStruct)
  private
    FKey: Integer;
    FValue: string;
    
    F__isset_Key: Boolean;
    F__isset_Value: Boolean;
    
    function GetKey: Integer;
    procedure SetKey( const Value: Integer);
    function GetValue: string;
    procedure SetValue( const Value: string);

    function Get__isset_Key: Boolean;
    function Get__isset_Value: Boolean;
  public
    constructor Create;
    destructor Destroy; override;

    function ToString: string; override;

    // IBase
    procedure Read( const iprot: IProtocol);
    procedure Write( const oprot: IProtocol);

    // Properties
    property Key: Integer read GetKey write SetKey;
    property Value: string read GetValue write SetValue;

    // isset
    property __isset_Key: Boolean read Get__isset_Key;
    property __isset_Value: Boolean read Get__isset_Value;
  end;

  TSharedService = class
  public
    type
      Iface = interface
        function getStruct(key: Integer): ISharedStruct;
      end;

      TClient = class( TInterfacedObject, Iface)
      public
        constructor Create( prot: IProtocol); overload;
        constructor Create( const iprot: IProtocol; const oprot: IProtocol); overload;
      protected
        iprot_: IProtocol;
        oprot_: IProtocol;
        seqid_: Integer;
      public
        property InputProtocol: IProtocol read iprot_;
        property OutputProtocol: IProtocol read oprot_;
      protected
        // Iface
        function getStruct(key: Integer): ISharedStruct;
      public
        procedure send_getStruct(key: Integer);
        function recv_getStruct(): ISharedStruct;
      end;

      TProcessorImpl = class( TInterfacedObject, IProcessor)
      public
        constructor Create( iface_: Iface );
        destructor Destroy; override;
      private
        iface_: Iface;
      protected
        type
          TProcessFunction = reference to procedure( seqid: Integer; const iprot: IProtocol; const oprot: IProtocol);
      protected
        processMap_: IThriftDictionary<string, TProcessFunction>;
      public
        function Process( const iprot: IProtocol; const oprot: IProtocol): Boolean;
        procedure getStruct_Process( seqid: Integer; const iprot: IProtocol; const oprot: IProtocol);
      end;

      IGetStruct_args = interface(IBase)
        function GetKey: Integer;
        procedure SetKey( const Value: Integer);

        property Key: Integer read GetKey write SetKey;

        function Get__isset_Key: Boolean;

        property __isset_Key: Boolean read Get__isset_Key;
      end;

      TGetStruct_argsImpl = class(TInterfacedObject, IBase, IGetStruct_args)
      private
        FKey: Integer;
        
        F__isset_Key: Boolean;
        
        function GetKey: Integer;
        procedure SetKey( const Value: Integer);

        function Get__isset_Key: Boolean;
      public
        constructor Create;
        destructor Destroy; override;

        function ToString: string; override;

        // IBase
        procedure Read( const iprot: IProtocol);
        procedure Write( const oprot: IProtocol);

        // Properties
        property Key: Integer read GetKey write SetKey;

        // isset
        property __isset_Key: Boolean read Get__isset_Key;
      end;

      IGetStruct_result = interface(IBase)
        function GetSuccess: ISharedStruct;
        procedure SetSuccess( const Value: ISharedStruct);

        property Success: ISharedStruct read GetSuccess write SetSuccess;

        function Get__isset_Success: Boolean;

        property __isset_Success: Boolean read Get__isset_Success;
      end;

      TGetStruct_resultImpl = class(TInterfacedObject, IBase, IGetStruct_result)
      private
        FSuccess: ISharedStruct;
        
        F__isset_Success: Boolean;
        
        function GetSuccess: ISharedStruct;
        procedure SetSuccess( const Value: ISharedStruct);

        function Get__isset_Success: Boolean;
      public
        constructor Create;
        destructor Destroy; override;

        function ToString: string; override;

        // IBase
        procedure Read( const iprot: IProtocol);
        procedure Write( const oprot: IProtocol);

        // Properties
        property Success: ISharedStruct read GetSuccess write SetSuccess;

        // isset
        property __isset_Success: Boolean read Get__isset_Success;
      end;

  end;
  
implementation

constructor TSharedStructImpl.Create;
begin
  inherited;
end;

destructor TSharedStructImpl.Destroy;
begin
  inherited;
end;

function TSharedStructImpl.GetKey: Integer;
begin
  Result := FKey;
end;

procedure TSharedStructImpl.SetKey( const Value: Integer);
begin
  F__isset_Key := True;
  FKey := Value;
end;

function TSharedStructImpl.Get__isset_Key: Boolean;
begin
  Result := F__isset_Key;
end;

function TSharedStructImpl.GetValue: string;
begin
  Result := FValue;
end;

procedure TSharedStructImpl.SetValue( const Value: string);
begin
  F__isset_Value := True;
  FValue := Value;
end;

function TSharedStructImpl.Get__isset_Value: Boolean;
begin
  Result := F__isset_Value;
end;

procedure TSharedStructImpl.Read( const iprot: IProtocol);
var
  field_ : IField;
  struc : IStruct;

begin
  struc := iprot.ReadStructBegin;
  try
    while (true) do
    begin
      field_ := iprot.ReadFieldBegin();
      if (field_.Type_ = TType.Stop) then
      begin
        Break;
      end;
      case field_.ID of
        1: begin
          if (field_.Type_ = TType.I32) then
          begin
            Key := iprot.ReadI32();
          end else
          begin
            TProtocolUtil.Skip(iprot, field_.Type_);
          end;
        end;
        2: begin
          if (field_.Type_ = TType.String_) then
          begin
            Value := iprot.ReadString();
          end else
          begin
            TProtocolUtil.Skip(iprot, field_.Type_);
          end;
        end
        else begin
          TProtocolUtil.Skip(iprot, field_.Type_);
        end;
      end;
      iprot.ReadFieldEnd;
    end;
  finally
    iprot.ReadStructEnd;
  end;
end;

procedure TSharedStructImpl.Write( const oprot: IProtocol);
var
  struc : IStruct;
  field_ : IField;
begin
  struc := TStructImpl.Create('SharedStruct');
  oprot.WriteStructBegin(struc);
  field_ := TFieldImpl.Create;
  if (__isset_Key) then
  begin
    field_.Name := 'key';
    field_.Type_  := TType.I32;
    field_.ID := 1;
    oprot.WriteFieldBegin(field_);
    oprot.WriteI32(Key);
    oprot.WriteFieldEnd();
  end;
  if (__isset_Value) then
  begin
    field_.Name := 'value';
    field_.Type_  := TType.String_;
    field_.ID := 2;
    oprot.WriteFieldBegin(field_);
    oprot.WriteString(Value);
    oprot.WriteFieldEnd();
  end;
  oprot.WriteFieldStop();
  oprot.WriteStructEnd();
end;

function TSharedStructImpl.ToString: string;
var
  sb : TThriftStringBuilder;
begin
  sb := TThriftStringBuilder.Create('(');
  try
    sb.Append('Key: ');
    sb.Append(Key);
    sb.Append(',Value: ');
    sb.Append(Value);
    sb.Append(')');
    Result := sb.ToString;
  finally
    sb.Free;
  end;
end;

constructor TSharedService.TClient.Create( prot: IProtocol);
begin
  Create( prot, prot );
end;

constructor TSharedService.TClient.Create( const iprot: IProtocol; const oprot: IProtocol);
begin
  iprot_ := iprot;
  oprot_ := oprot;
end;

function TSharedService.TClient.getStruct(key: Integer): ISharedStruct;
begin
  send_getStruct(key);
  Result := recv_getStruct();
end;

procedure TSharedService.TClient.send_getStruct(key: Integer);
var
  args : IGetStruct_args;
  msg : IMessage;
begin
  seqid_ := seqid_ + 1;
  msg := TMessageImpl.Create('getStruct', TMessageType.Call, seqid_);
  oprot_.WriteMessageBegin( msg );
  args := TGetStruct_argsImpl.Create();
  args.Key := key;
  args.Write(oprot_);
  args.Key := 0;
  oprot_.WriteMessageEnd();
  oprot_.Transport.Flush();
end;

function TSharedService.TClient.recv_getStruct(): ISharedStruct;
var
  msg : IMessage;
  x : TApplicationException;
  ret : IGetStruct_result;
begin
  msg := iprot_.ReadMessageBegin();
  if (msg.Type_ = TMessageType.Exception) then
  begin
    x := TApplicationException.Read(iprot_);
    iprot_.ReadMessageEnd();
    raise x;
  end;
  ret := TGetStruct_resultImpl.Create();
  ret.Read(iprot_);
  iprot_.ReadMessageEnd();
  if (ret.__isset_success) then
  begin
    Result := ret.Success;
    ret.Success := nil;
    Exit;
  end;
  raise TApplicationException.Create(TApplicationException.TExceptionType.MissingResult, 'getStruct failed: unknown result');
end;

constructor TSharedService.TProcessorImpl.Create( iface_: Iface );
begin
  inherited Create;
  Self.iface_ := iface_;
  processMap_ := TThriftDictionaryImpl<string, TProcessFunction>.Create;
  processMap_.AddOrSetValue( 'getStruct', getStruct_Process);
end;

destructor TSharedService.TProcessorImpl.Destroy;
begin
  inherited;
end;

function TSharedService.TProcessorImpl.Process( const iprot: IProtocol; const oprot: IProtocol): Boolean;
var
  msg : IMessage;
  fn : TProcessFunction;
  x : TApplicationException;
begin
  try
    msg := iprot.ReadMessageBegin();
    fn := nil;
    if not processMap_.TryGetValue(msg.Name, fn)
    or not Assigned(fn) then
    begin
      TProtocolUtil.Skip(iprot, TType.Struct);
      iprot.ReadMessageEnd();
      x := TApplicationException.Create(TApplicationException.TExceptionType.UnknownMethod, 'Invalid method name: ''' + msg.Name + '''');
      msg := TMessageImpl.Create(msg.Name, TMessageType.Exception, msg.SeqID);
      oprot.WriteMessageBegin( msg);
      x.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
      Result := True;
      Exit;
    end;
    fn(msg.SeqID, iprot, oprot);
  except
    Result := False;
    Exit;
  end;
  Result := True;
end;

// both way processor
procedure TSharedService.TProcessorImpl.getStruct_Process( seqid: Integer; const iprot: IProtocol; const oprot: IProtocol);
var
  args: IGetStruct_args;
  msg: IMessage;
  ret: IGetStruct_result;
begin
  args := TGetStruct_argsImpl.Create;
  args.Read(iprot);
  iprot.ReadMessageEnd();
  ret := TGetStruct_resultImpl.Create;
  ret.Success := iface_.getStruct(args.Key);
  args.Key := 0;
  msg := TMessageImpl.Create('getStruct', TMessageType.Reply, seqid); 
  oprot.WriteMessageBegin( msg); 
  ret.Write(oprot);
  oprot.WriteMessageEnd();
  oprot.Transport.Flush();
end;

constructor TSharedService.TGetStruct_argsImpl.Create;
begin
  inherited;
end;

destructor TSharedService.TGetStruct_argsImpl.Destroy;
begin
  inherited;
end;

function TSharedService.TGetStruct_argsImpl.GetKey: Integer;
begin
  Result := FKey;
end;

procedure TSharedService.TGetStruct_argsImpl.SetKey( const Value: Integer);
begin
  F__isset_Key := True;
  FKey := Value;
end;

function TSharedService.TGetStruct_argsImpl.Get__isset_Key: Boolean;
begin
  Result := F__isset_Key;
end;

procedure TSharedService.TGetStruct_argsImpl.Read( const iprot: IProtocol);
var
  field_ : IField;
  struc : IStruct;

begin
  struc := iprot.ReadStructBegin;
  try
    while (true) do
    begin
      field_ := iprot.ReadFieldBegin();
      if (field_.Type_ = TType.Stop) then
      begin
        Break;
      end;
      case field_.ID of
        1: begin
          if (field_.Type_ = TType.I32) then
          begin
            Key := iprot.ReadI32();
          end else
          begin
            TProtocolUtil.Skip(iprot, field_.Type_);
          end;
        end
        else begin
          TProtocolUtil.Skip(iprot, field_.Type_);
        end;
      end;
      iprot.ReadFieldEnd;
    end;
  finally
    iprot.ReadStructEnd;
  end;
end;

procedure TSharedService.TGetStruct_argsImpl.Write( const oprot: IProtocol);
var
  struc : IStruct;
  field_ : IField;
begin
  struc := TStructImpl.Create('getStruct_args');
  oprot.WriteStructBegin(struc);
  field_ := TFieldImpl.Create;
  if (__isset_Key) then
  begin
    field_.Name := 'key';
    field_.Type_  := TType.I32;
    field_.ID := 1;
    oprot.WriteFieldBegin(field_);
    oprot.WriteI32(Key);
    oprot.WriteFieldEnd();
  end;
  oprot.WriteFieldStop();
  oprot.WriteStructEnd();
end;

function TSharedService.TGetStruct_argsImpl.ToString: string;
var
  sb : TThriftStringBuilder;
begin
  sb := TThriftStringBuilder.Create('(');
  try
    sb.Append('Key: ');
    sb.Append(Key);
    sb.Append(')');
    Result := sb.ToString;
  finally
    sb.Free;
  end;
end;

constructor TSharedService.TGetStruct_resultImpl.Create;
begin
  inherited;
end;

destructor TSharedService.TGetStruct_resultImpl.Destroy;
begin
  inherited;
end;

function TSharedService.TGetStruct_resultImpl.GetSuccess: ISharedStruct;
begin
  Result := FSuccess;
end;

procedure TSharedService.TGetStruct_resultImpl.SetSuccess( const Value: ISharedStruct);
begin
  F__isset_Success := True;
  FSuccess := Value;
end;

function TSharedService.TGetStruct_resultImpl.Get__isset_Success: Boolean;
begin
  Result := F__isset_Success;
end;

procedure TSharedService.TGetStruct_resultImpl.Read( const iprot: IProtocol);
var
  field_ : IField;
  struc : IStruct;

begin
  struc := iprot.ReadStructBegin;
  try
    while (true) do
    begin
      field_ := iprot.ReadFieldBegin();
      if (field_.Type_ = TType.Stop) then
      begin
        Break;
      end;
      case field_.ID of
        0: begin
          if (field_.Type_ = TType.Struct) then
          begin
            Success := TSharedStructImpl.Create;
            Success.Read(iprot);
          end else
          begin
            TProtocolUtil.Skip(iprot, field_.Type_);
          end;
        end
        else begin
          TProtocolUtil.Skip(iprot, field_.Type_);
        end;
      end;
      iprot.ReadFieldEnd;
    end;
  finally
    iprot.ReadStructEnd;
  end;
end;

procedure TSharedService.TGetStruct_resultImpl.Write( const oprot: IProtocol);
var
  struc : IStruct;
  field_ : IField;
begin
  struc := TStructImpl.Create('getStruct_result');
  oprot.WriteStructBegin(struc);
  field_ := TFieldImpl.Create;
  if (Success <> nil) and __isset_Success then
  begin
    field_.Name := 'Success';
    field_.Type_  := TType.Struct;
    field_.ID := 0;
    oprot.WriteFieldBegin(field_);
    Success.Write(oprot);
    oprot.WriteFieldEnd();
  end;
  oprot.WriteFieldStop();
  oprot.WriteStructEnd();
end;

function TSharedService.TGetStruct_resultImpl.ToString: string;
var
  sb : TThriftStringBuilder;
begin
  sb := TThriftStringBuilder.Create('(');
  try
    sb.Append('Success: ');
    if (Success = nil) then sb.Append('<null>') else sb.Append(Success.ToString());
    sb.Append(')');
    Result := sb.ToString;
  finally
    sb.Free;
  end;
end;


initialization

finalization


end.
